# src/fugue/Makefile.tmpl --- IcIES/Fugue Makefile.am template
# Maintainer:  SAITO Fuyuki
# Created: Aug 19 2013
# Revision:  Snoopy0.97
# Time-stamp: <2020/09/17 06:49:02 fuyuki Makefile.tmpl>

# Copyright: 2013--2020 JAMSTEC, Ayako ABE-OUCHI
# Licensed under the Apache License, Version 2.0
#   (https://www.apache.org/licenses/LICENSE-2.0)

libicies_local_la_ORIGINS	= fbrdgi.F fvarms.F
EXTRA_SRCS	=

LIB_DEPEND_DIRS	=	arpeggio development unison

### Local Variables:
### mode: makefile-automake
### end:
