# src/rhythm/Makefile.tmpl --- IcIES/Rhythm Makefile.am template
# Maintainer:  SAITO Fuyuki
# Created: Nov 16 2019
# Revision:  Snoopy0.97
# Time-stamp: <2020/09/17 06:49:31 fuyuki Makefile.tmpl>

# Copyright: 2019--2020 JAMSTEC, Ayako ABE-OUCHI
# Licensed under the Apache License, Version 2.0
#   (https://www.apache.org/licenses/LICENSE-2.0)

libicies_local_la_ORIGINS	=	rtmtmp.F

LIB_DEPEND_DIRS	=	unison

### Local Variables:
### mode: makefile-automake
### end:
