# arpeggio/Makefile.tmpl --- Arpeggio Makefile.am template
# Maintainer:  SAITO Fuyuki
# Created: Nov 4 2011
# Revision:  Arpeggio 1.0
# Time-stamp: <2020/09/15 22:30:01 fuyuki Makefile.tmpl>

# Copyright: 2011--2020 JAMSTEC
# Licensed under the Apache License, Version 2.0
#   (https://www.apache.org/licenses/LICENSE-2.0)

libicies_local_la_ORIGINS	= acorms.F agmtry.F aedlra.F akwopr.F afintf.F apscfg.F arpmng.F
EXTRA_SRCS =

LIB_DEPEND_DIRS	=	development unison

### Local Variables:
### mode: makefile-automake
### end:
