#!/bin/sh
# Time-stamp: <2020/09/15 12:25:24 fuyuki post-merge>
# Copyright: 2011--2020 JAMSTEC
# Licensed under the Apache License, Version 2.0
#   (https://www.apache.org/licenses/LICENSE-2.0)
a=$1
. `git --exec-path`/git-sh-setup
cd_to_toplevel
cmd=build-aux/icies/tree-all
test -x $cmd && $cmd
