#!/bin/sh
# Time-stamp: <2021/04/18 23:30:41 fuyuki post-merge>
# Copyright: 2011-2021 JAMSTEC
# Licensed under the Apache License, Version 2.0
#   (https://www.apache.org/licenses/LICENSE-2.0)
a=$1
. `git --exec-path`/git-sh-setup
cd_to_toplevel
cmd=build-aux/icies/idgen
test -x $cmd && $cmd TreeID
