# IcIES/src/begleitung
# Author: SAITO Fuyuki
# Created: Aug 8 2013
# Time-stamp: <2020/09/15 11:03:22 fuyuki Makefile.tmpl>

# Copyright: 2013--2020 JAMSTEC, Ayako ABE-OUCHI
# Licensed under the Apache License, Version 2.0
#   (https://www.apache.org/licenses/LICENSE-2.0)

libicies_local_la_ORIGINS	= bglbrt.F

BUILT_SOURCES	=	begleitung.h
EXTRA_DIST  	=	begleitung.m4 $(BUILT_SOURCES) ##%% a
MAINTAINERCLEANFILES = $(BUILT_SOURCES)  ##%% a


SQIHELP	= $(top_srcdir)/build-aux/icies/sqihelp
if MAINTAINER_MODE
begleitung.h: begleitung.m4
	$(SQIHELP) -o $@ $<
else
begleitung.h: begleitung.m4
	@if test -f $@; then \
		echo keep $@; \
	elif test -f $(srcdir)/$@; then \
		$(CP) $(srcdir)/$@ $(builddir); \
	else \
		$(SQIHELP) -o $@ $<; \
	fi
endif

### Local Variables:
### mode: makefile-automake
### end:
