#!/bin/sh
# Time-stamp: <2021/04/19 08:33:20 fuyuki bootstrap>
# Copyright: 2011-2021 JAMSTEC
# Licensed under the Apache License, Version 2.0
#   (https://www.apache.org/licenses/LICENSE-2.0)

d=`dirname "$0"`

MAGIC='It was a dark and stormy night'

DEFS="auto-all tree-all"
OPTS="hooks-all"

CMDS="$DEFS"
test x"$1" = x-m && shift && CMDS="$CMDS $OPTS"

if test "$1" = "$MAGIC"; then
  :
else
  cat << EOF >&2
-----------------------
 bootstrap for IcIES-2
-----------------------
This script calls some scripts to construct files on clean resources
obtained from, e.g., git repository.  Mostly you do not have to run
this script, in particular, when you obtain the resources as a tar
archive file.

  $d/auto-all - generate 'Makefile.am's from 'Makefile.tmpl's, and run 'autoreconf'
  $d/tree-all - generate TreeID to record revision properties
  $d/hooks-all - install files in $d/hooks as githooks

In case you doubt, please confirm the scripts.

If you are sure, *rerun* this script with a magic argument:

   $0 '$MAGIC'        # run {$DEFS}
   $0 -m '$MAGIC'     # also run {$OPTS}

Note that you may need to quote the argument to be interpreted as single.

----------------------------------------
$0: aborted
----------------------------------------
EOF
  exit 1
fi

echo "$0: start..."
for c in $CMDS
do
  c=$d/$c
  if test -x "$c"; then
    echo "$0: run '$c'" >&2
    $c; e=$?
     if test $e -ne 0 ; then
       echo "$0: failed while '$c'" >&2
       echo "$0: err=$e" >&2
       exit $e
     fi
  fi
done
echo "$0: done"
exit 0
