#!/usr/bin/zsh -f
# Time-stamp: <2020/09/17 08:31:02 fuyuki header>

opts=()

while [[ $# -gt 0 ]]
do
  case $1 in
  (-h) mode=h;;
  (-i) opts+=($1);;
  (*)  break;;
  esac
  shift
done

for f in $@
do
  x=$f:e
  print -u2 - $x $f
  case $x in
  (F) PFX="C " SFX='';;
  (h) PFX="C " SFX='';;
  (*) print -u2 - "Skip $f"; continue
  esac
  if [[ $mode == h ]]; then
    PFX="/* " SFX=" */"
    grep --quiet '^[Cc]' $f && print -u2 - "Skip $f" && continue
  fi
  # sed [cia] commands not work as expected....
  h=$(sed -n "/This file is.*IcIES/=" $f)
  e=$(sed -n "/You cannot.*group/=" $f)
  print -u2 - "## $f $h $e"
  if [[ -n $h && -n $e ]]; then
      sed $opts \
          -e '/Copyright/s/--[0-9][0-9][0-9][0-9]/--2020/' \
          -e '/Copyright/s/\( [0-9][0-9][0-9][0-9]\)$/\1--2020/' \
          -e ${h},${e}d \
          -e "$((e+1))i\\
${PFX}Licensed under the Apache License, Version 2.0${SFX}\\
${PFX}  (https://www.apache.org/licenses/LICENSE-2.0)${SFX}" $f
  fi
done
