#!/usr/bin/zsh -f
# Time-stamp: <2019/12/17 13:54:22 fuyuki sqihelp>

: ${AUTOM4TE:=autom4te}

###_ functions
###_. help
show_usage ()
{
  exit 0
}

###_ main

###_. argument parser

while getopts fqvhno:t: o
do
  case $o in
  f) force=T;;
  v) verbose=1;;
  q) verbose=-1;;
  h) help=T;;
  n) dry=T;;
  o) outf=$OPTARG;;
  t) otype=$OPTARG;;
  *) print -u2 "invalid argument";;
  esac
done
shift $((OPTIND-1))

[[ -n $help ]] && show_usage && exit 0

: ${verbose:=0}
bindir=$0:h
m4hdir=$bindir/m4

amopts=(-l M4sugar)
[[ -n $outf ]] && amopts=($amopts -o $outf)

# output type
if   [[ $otype == e* ]];then
  # shell/export
  :
elif [[ $otype == s* ]];then
  # shell
  cfgh=$m4hdir/sqishell.m4
elif [[ $otype == a* ]];then
  # shell, associative array
  cfgh=$m4hdir/sqiaarray.m4
elif [[ $otype == p* ]];then
  # shell, associative array
  cfgh=$m4hdir/sqiplist.m4
elif [[ $otype == t* ]];then
  # trace/cpp
  amopts=(-t '_dummy:$ %' $amopts)
else
  # default cpp-macro
  :
fi


m4h=$m4hdir/sqidef.m4

${AUTOM4TE} $amopts $cfgh $m4h $@
