#!/bin/sh
# Maintainer: SAITO Fuyuki
# Time-stamp: <2021/04/19 08:12:38 fuyuki tree-all>
# Copyright: 2011-2021 JAMSTEC
# Licensed under the Apache License, Version 2.0
#   (https://www.apache.org/licenses/LICENSE-2.0)

bindir=`dirname "$0"`

top_srcdir=
if command -v "git" > /dev/null 2>&1; then
  chk=`git rev-parse --is-inside-work-tree 2> /dev/null || echo false`
  if test x"$chk" = xtrue; then
    top_srcdir=`git rev-parse --show-toplevel` || exit $?
  fi
fi
test x"$top_srcdir" = x && top_srcdir=${bindir}/../..

idgen=$bindir/idgen

test -x $idgen || { echo "Cannot run $idgen." >&2; exit 1; }

$idgen $top_srcdir/TreeID || exit $?
exit 0
