# src/Makefile.tmpl --- IcIES src/Makefile.am template
# Maintainer:  SAITO Fuyuki
# Created: Nov 2 2011
# Revision:  Snoopy0.97
# Time-stamp: <2020/09/17 06:49:53 fuyuki Makefile.tmpl>

# Copyright: 2011--2020 JAMSTEC, Ayako ABE-OUCHI
# Licensed under the Apache License, Version 2.0
#   (https://www.apache.org/licenses/LICENSE-2.0)

bin_PROGRAMS_ORIGINS	=	icies.F iciesa.F icies_tgv.F

if MAINTAINER_MODE
bin_PROGRAMS = icies iciesa   ##%% t
endif


iciesa_LDADD		= 	libicies.la
icies_LDADD			= 	libicies.la
icies_tgv_LDADD		=	libicies.la

lib_LTLIBRARIES = libicies.la
libicies_la_SOURCES =
# nodist_EXTRA_libicies_la_SOURCES = dummy.F

LIB_DEPEND_DIRS	=	unison development arpeggio movement begleitung rhythm fugue
# # fugue
# if MAINTAINER_MODE
# LIB_DEPEND_DIRS +=
# endif

libicies_la_LIBADD = unison/libicies_local.la development/libicies_local.la arpeggio/libicies_local.la movement/libicies_local.la begleitung/libicies_local.la rhythm/libicies_local.la
if MAINTAINER_MODE
libicies_la_LIBADD += fugue/libicies_local.la
endif
## begleitung/libicies_local.la

SUBDIRS       = $(LIB_DEPEND_DIRS) ##%% t
DIST_SUBDIRS  = $(SUBDIRS) ostinato cadenza

noinst_LTLIBRARIES	=	##%% n
## nodist_libicies_local_la_SOURCES	=	##%% n

# force nullify
LCLCNDH	= ##%% t

install-cadenza:
	@cd cadenza; $(MAKE) $(AM_MAKEFLAGS) all install

### Local Variables:
### mode: makefile-automake
### end:
