# src/ostinato/Makefile.tmpl --- IcIES/Ostinato Makefile.am template
# Maintainer:  SAITO Fuyuki
# Created: Nov 4 2011
# Revision:  Snoopy0.9
# Time-stamp: <2020/09/15 11:02:26 fuyuki Makefile.tmpl>

# Copyright: 2011--2020 JAMSTEC, Ayako ABE-OUCHI
# Licensed under the Apache License, Version 2.0
#   (https://www.apache.org/licenses/LICENSE-2.0)

GCLDEF	=	gcldef.h

EXTRA_DIST = ##%% a
EXTRA_DIST += ofdlct.h ofnstd.h ologfm.h orevan.h olimit.h \
			ounits.h ouhcal.h ounelv.h \
			odevel.h odevid.h odevva.h \
			oarpea.h oarpea_obsolete256.h oarpea_v257.h oarpkw.h oarpfi.h oarpgc.h ovconf.h \
			ofugca.h \
			oclock.h $(GCLDEF)
# force nullify
LCLCNDH	= ##%% t

$(GCLDEF):
	touch $@

### Local Variables:
### mode: makefile-automake
### end:
